CREATE TABLE IF NOT EXISTS schema_migrations (
    version BIGINT PRIMARY KEY,
    dirty BOOLEAN NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "order_number" varchar UNIQUE NOT NULL,
  "status" varchar NOT NULL,
  "accrual" float DEFAULT 0,
  "uploaded_at" timestamp DEFAULT (now())
);

CREATE TABLE "loyalty_accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE,
  "current_balance" float NOT NULL DEFAULT 0,
  "withdrawn_balance" float NOT NULL DEFAULT 0,
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "loyalty_transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" int,
  "order_id" int,
  "points" float NOT NULL,
  "transaction_type" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "withdrawals" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "order_number" varchar NOT NULL,
  "sum" float NOT NULL,
  "processed_at" timestamp DEFAULT (now())
);

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "loyalty_accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "loyalty_transactions" ADD FOREIGN KEY ("account_id") REFERENCES "loyalty_accounts" ("id");

ALTER TABLE "loyalty_transactions" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "withdrawals" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");