// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: balance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWithdrawal = `-- name: CreateWithdrawal :exec
INSERT INTO withdrawals (user_id, order_number, sum)
VALUES ($1, $2, $3)
`

type CreateWithdrawalParams struct {
	UserID      pgtype.Int4 `json:"user_id"`
	OrderNumber string      `json:"order_number"`
	Sum         float64     `json:"sum"`
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) error {
	_, err := q.db.Exec(ctx, createWithdrawal, arg.UserID, arg.OrderNumber, arg.Sum)
	return err
}

const getBalanceByUserID = `-- name: GetBalanceByUserID :one
SELECT current_balance, withdrawn_balance
FROM loyalty_accounts
WHERE user_id = $1
LIMIT 1
FOR UPDATE
`

type GetBalanceByUserIDRow struct {
	CurrentBalance   pgtype.Numeric `json:"current_balance"`
	WithdrawnBalance pgtype.Numeric `json:"withdrawn_balance"`
}

func (q *Queries) GetBalanceByUserID(ctx context.Context, userID pgtype.Int4) (GetBalanceByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getBalanceByUserID, userID)
	var i GetBalanceByUserIDRow
	err := row.Scan(&i.CurrentBalance, &i.WithdrawnBalance)
	return i, err
}

const getWithdrawalsByUserID = `-- name: GetWithdrawalsByUserID :many
SELECT order_number, user_id, sum, processed_at 
FROM withdrawals 
WHERE user_id = $1
ORDER BY processed_at DESC
`

type GetWithdrawalsByUserIDRow struct {
	OrderNumber string           `json:"order_number"`
	UserID      pgtype.Int4      `json:"user_id"`
	Sum         float64          `json:"sum"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}

func (q *Queries) GetWithdrawalsByUserID(ctx context.Context, userID pgtype.Int4) ([]GetWithdrawalsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getWithdrawalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWithdrawalsByUserIDRow{}
	for rows.Next() {
		var i GetWithdrawalsByUserIDRow
		if err := rows.Scan(
			&i.OrderNumber,
			&i.UserID,
			&i.Sum,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE loyalty_accounts
SET current_balance = $2, withdrawn_balance = $3
WHERE user_id = $1
`

type UpdateBalanceParams struct {
	UserID           pgtype.Int4    `json:"user_id"`
	CurrentBalance   pgtype.Numeric `json:"current_balance"`
	WithdrawnBalance pgtype.Numeric `json:"withdrawn_balance"`
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance, arg.UserID, arg.CurrentBalance, arg.WithdrawnBalance)
	return err
}
