// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LoyaltyAccount struct {
	ID               int32            `json:"id"`
	UserID           pgtype.Int4      `json:"user_id"`
	CurrentBalance   float64          `json:"current_balance"`
	WithdrawnBalance float64          `json:"withdrawn_balance"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type LoyaltyTransaction struct {
	ID              int32            `json:"id"`
	AccountID       pgtype.Int4      `json:"account_id"`
	OrderID         pgtype.Int4      `json:"order_id"`
	Points          float64          `json:"points"`
	TransactionType string           `json:"transaction_type"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID          int32            `json:"id"`
	UserID      pgtype.Int4      `json:"user_id"`
	OrderNumber string           `json:"order_number"`
	Status      string           `json:"status"`
	Accrual     pgtype.Float8    `json:"accrual"`
	UploadedAt  pgtype.Timestamp `json:"uploaded_at"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}

type User struct {
	ID       int32  `json:"id"`
	Login    string `json:"login"`
	Password string `json:"password"`
}

type Withdrawal struct {
	ID          int32            `json:"id"`
	UserID      pgtype.Int4      `json:"user_id"`
	OrderNumber string           `json:"order_number"`
	Sum         float64          `json:"sum"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}
