// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id, 
    order_number, 
    status
    ) VALUES ($1, $2, $3)
RETURNING id, user_id, order_number, status, accrual, uploaded_at
`

type CreateOrderParams struct {
	UserID      pgtype.Int4 `json:"user_id"`
	OrderNumber string      `json:"order_number"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.OrderNumber, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderNumber,
		&i.Status,
		&i.Accrual,
		&i.UploadedAt,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT id, user_id, order_number, status, accrual, uploaded_at FROM orders
WHERE order_number = $1 LIMIT 1
`

func (q *Queries) GetOrderByNumber(ctx context.Context, orderNumber string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, orderNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderNumber,
		&i.Status,
		&i.Accrual,
		&i.UploadedAt,
	)
	return i, err
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT order_number, status, accrual, uploaded_at
FROM orders
WHERE user_id = $1
ORDER BY uploaded_at DESC
`

type GetOrdersByUserIDRow struct {
	OrderNumber string           `json:"order_number"`
	Status      string           `json:"status"`
	Accrual     pgtype.Float8    `json:"accrual"`
	UploadedAt  pgtype.Timestamp `json:"uploaded_at"`
}

func (q *Queries) GetOrdersByUserID(ctx context.Context, userID pgtype.Int4) ([]GetOrdersByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrdersByUserIDRow{}
	for rows.Next() {
		var i GetOrdersByUserIDRow
		if err := rows.Scan(
			&i.OrderNumber,
			&i.Status,
			&i.Accrual,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessedOrdersByUserID = `-- name: GetProcessedOrdersByUserID :many
SELECT order_number, user_id, status, accrual, uploaded_at
FROM orders
WHERE user_id = $1 AND status = 'PROCESSED'
ORDER BY uploaded_at DESC
`

type GetProcessedOrdersByUserIDRow struct {
	OrderNumber string           `json:"order_number"`
	UserID      pgtype.Int4      `json:"user_id"`
	Status      string           `json:"status"`
	Accrual     pgtype.Float8    `json:"accrual"`
	UploadedAt  pgtype.Timestamp `json:"uploaded_at"`
}

func (q *Queries) GetProcessedOrdersByUserID(ctx context.Context, userID pgtype.Int4) ([]GetProcessedOrdersByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getProcessedOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProcessedOrdersByUserIDRow{}
	for rows.Next() {
		var i GetProcessedOrdersByUserIDRow
		if err := rows.Scan(
			&i.OrderNumber,
			&i.UserID,
			&i.Status,
			&i.Accrual,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnprocessedOrders = `-- name: GetUnprocessedOrders :many

SELECT id, order_number, status 
FROM orders 
WHERE status NOT IN ('PROCESSED', 'INVALID')
`

type GetUnprocessedOrdersRow struct {
	ID          int32  `json:"id"`
	OrderNumber string `json:"order_number"`
	Status      string `json:"status"`
}

// -- name: GetProcessedOrdersByUserID :many
// SELECT order_number, user_id, status, accrual, uploaded_at
// FROM orders
// WHERE user_id = $1 AND status = 'PROCESSED';
func (q *Queries) GetUnprocessedOrders(ctx context.Context) ([]GetUnprocessedOrdersRow, error) {
	rows, err := q.db.Query(ctx, getUnprocessedOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnprocessedOrdersRow{}
	for rows.Next() {
		var i GetUnprocessedOrdersRow
		if err := rows.Scan(&i.ID, &i.OrderNumber, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
