// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoyaltyTransaction = `-- name: CreateLoyaltyTransaction :exec
INSERT INTO loyalty_transactions (
    account_id,
    order_id,
    points,
    transaction_type,
    created_at
)
VALUES (
    $1, $2, $3, $4, NOW()
)
`

type CreateLoyaltyTransactionParams struct {
	AccountID       pgtype.Int4 `json:"account_id"`
	OrderID         pgtype.Int4 `json:"order_id"`
	Points          float64     `json:"points"`
	TransactionType string      `json:"transaction_type"`
}

func (q *Queries) CreateLoyaltyTransaction(ctx context.Context, arg CreateLoyaltyTransactionParams) error {
	_, err := q.db.Exec(ctx, createLoyaltyTransaction,
		arg.AccountID,
		arg.OrderID,
		arg.Points,
		arg.TransactionType,
	)
	return err
}

const getLoyaltyAccountID = `-- name: GetLoyaltyAccountID :one
SELECT id
FROM loyalty_accounts
WHERE user_id = $1
`

func (q *Queries) GetLoyaltyAccountID(ctx context.Context, userID pgtype.Int4) (int32, error) {
	row := q.db.QueryRow(ctx, getLoyaltyAccountID, userID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrderID = `-- name: GetOrderID :one
SELECT id
FROM orders
WHERE order_number = $1
`

func (q *Queries) GetOrderID(ctx context.Context, orderNumber string) (int32, error) {
	row := q.db.QueryRow(ctx, getOrderID, orderNumber)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrderOwner = `-- name: GetOrderOwner :one
SELECT user_id
FROM orders
WHERE order_number = $1
`

func (q *Queries) GetOrderOwner(ctx context.Context, orderNumber string) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getOrderOwner, orderNumber)
	var user_id pgtype.Int4
	err := row.Scan(&user_id)
	return user_id, err
}

const saveOrder = `-- name: SaveOrder :exec
INSERT INTO orders (
    user_id,
    order_number,
    status,
    accrual,
    uploaded_at
)
VALUES (
    $1, $2, $3, $4, NOW()
)
`

type SaveOrderParams struct {
	UserID      pgtype.Int4   `json:"user_id"`
	OrderNumber string        `json:"order_number"`
	Status      string        `json:"status"`
	Accrual     pgtype.Float8 `json:"accrual"`
}

func (q *Queries) SaveOrder(ctx context.Context, arg SaveOrderParams) error {
	_, err := q.db.Exec(ctx, saveOrder,
		arg.UserID,
		arg.OrderNumber,
		arg.Status,
		arg.Accrual,
	)
	return err
}

const updateLoyaltyAccountBalance = `-- name: UpdateLoyaltyAccountBalance :exec
UPDATE loyalty_accounts
SET
    current_balance = current_balance + $1,
    updated_at = NOW()
WHERE
    user_id = $2
`

type UpdateLoyaltyAccountBalanceParams struct {
	CurrentBalance pgtype.Numeric `json:"current_balance"`
	UserID         pgtype.Int4    `json:"user_id"`
}

func (q *Queries) UpdateLoyaltyAccountBalance(ctx context.Context, arg UpdateLoyaltyAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateLoyaltyAccountBalance, arg.CurrentBalance, arg.UserID)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET
    status = $1,
    accrual = $2
WHERE
    order_number = $3
`

type UpdateOrderStatusParams struct {
	Status      string        `json:"status"`
	Accrual     pgtype.Float8 `json:"accrual"`
	OrderNumber string        `json:"order_number"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.Status, arg.Accrual, arg.OrderNumber)
	return err
}
